name: Trigger auto deployment for creditscoreservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ api-dev ]
    paths:
    - '**'
    - '.github/workflows/creditscoreservice-AutoDeployTrigger-74035dcf-6d6c-4ab8-8a24-b589df61fd6d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDITSCORESERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: creditscorecr.azurecr.io
          registryUsername: ${{ secrets.CREDITSCORESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CREDITSCORESERVICE_REGISTRY_PASSWORD }}
          containerAppName: creditscoreservice
          resourceGroup: personalprojects
          imageToBuild: creditscorecr.azurecr.io/creditscoreservice:${{ github.sha }}